version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    target-branch: "v1.2"
    directory: "/"
    schedule:
      interval: "daily"
